MedLab_Dapper/Controllers/AboutController.cs
using MedLab_Dapper.Dtos.AboutDtos;
using MedLab_Dapper.Repositories.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace MedLab_Dapper.Controllers;

[Route("Admin/[controller]/{action=Index}/{id?}")]
public class AboutController : Controller
{
    private readonly IRepositoryManager _repositoryManager;
    public AboutController(IRepositoryManager repositoryManager)
    {
        _repositoryManager = repositoryManager;
    }

    // GET: AboutController
    public async Task<ActionResult> Index()
    {
        var abouts= await _repositoryManager.About.GetAllAsync();
        return View(abouts);
    }

    // GET: AboutController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: AboutController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(CreateAboutDto about)
    {
        try
        {
            await _repositoryManager.About.CreateAsync(about);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View(about);
        }
    }

    // GET: AboutController/Edit/5
    public async Task<ActionResult> Update(int id)
    {
        var about = await _repositoryManager.About.GetByIdAsync(id);
        return View(about);
    }

    // POST: AboutController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Update(UpdateAboutDto update)
    {
        try
        {
            await _repositoryManager.About.UpdateAsync(update);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View(update);
        }
    }

    // GET: AboutController/Delete/5
    public async Task<ActionResult> Delete(int id)
    {
        await _repositoryManager.About.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }

    // POST: AboutController/Delete/5
  
}

MedLab_Dapper/Controllers/ContactController.cs
using System.Threading.Tasks;
using MedLab_Dapper.Dtos.ContactDtos;
using MedLab_Dapper.Repositories.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace MedLab_Dapper.Controllers;

[Route("Admin/[controller]/{action=Index}/{id?}")]
public class ContactController : Controller
{
    private readonly IRepositoryManager _manager;
    public ContactController(IRepositoryManager manager)
    {
        _manager = manager;
    }

    public async Task<IActionResult> Index()
    {
        var contacts = await _manager.Contact.GetAllAsync();
        return View(contacts);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateContactDto contact)
    {
        if (!ModelState.IsValid)
            return View(contact);
        await _manager.Contact.CreateAsync(contact);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Update(int id)
    {
        var contact = await _manager.Contact.GetByIdAsync(id);
        return View(contact);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateAsync(UpdateContactDto contact)
    {
        if (!ModelState.IsValid) return View(contact);
        await _manager.Contact.UpdateAsync(contact);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _manager.Contact.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

MedLab_Dapper/Controllers/GalleryController.cs
using MedLab_Dapper.Dtos.GalleryDtos;
using MedLab_Dapper.Repositories.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace MedLab_Dapper.Controllers;
[Route("Admin/[controller]/{action=Index}/{id?}")]
public class GalleryController : Controller
{
    private readonly IRepositoryManager _manager;

    public GalleryController(IRepositoryManager manager)
    {
        _manager = manager;
    }

    public async Task<IActionResult> Index()
    {
        var galleries = await _manager.Gallery.GetAllAsync();
        return View(galleries);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateGalleryDto gallery)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Invalid data provided.");
            return View(gallery);
        }
        await _manager.Gallery.CreateAsync(gallery);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Update(int id)
    {
        var gallery = await _manager.Gallery.GetByIdAsync(id);
        return View(gallery);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(GalleryDto gallery)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Invalid data provided.");
            return View(gallery);
        }
        await _manager.Gallery.UpdateAsync(gallery);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _manager.Gallery.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

MedLab_Dapper/Controllers/ItemController.cs
using MedLab_Dapper.Dtos.ItemDtos;
using MedLab_Dapper.Repositories.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedLab_Dapper.Controllers;

[Route("Admin/[controller]/{action=Index}/{id?}")]
public class ItemController : Controller
{

    private readonly IRepositoryManager _repositoryManager;
    public ItemController(IRepositoryManager repositoryManager)
    {
        _repositoryManager = repositoryManager;
    }

    // GET: ItemController
    public async Task<ActionResult> Index()
    {
        var items = await _repositoryManager.Item.GetAllAsync();
        return View(items);
    }

    // GET: ItemController/Create
    public async Task<ActionResult> Create()
    {
        await GetAboutsAsync();
        return View();
    }

    private async Task GetAboutsAsync()
    {
        var abouts=await _repositoryManager.About.GetAllAsync();
        ViewBag.Abouts = (from about in abouts
                          select new SelectListItem
                          {
                              Text=about.AboutId.ToString(),
                              Value=about.AboutId.ToString()
                          }).ToList();

    }

    // POST: ItemController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(CreateItemDto item)
    {
        try
        {
            await _repositoryManager.Item.CreateAsync(item);
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            await GetAboutsAsync();
            return View();
        }
    }

    // GET: ItemController/Edit/5
    public async Task<ActionResult> Update(int id)
    {
        var item = await _repositoryManager.Item.GetByIdAsync(id);
        await GetAboutsAsync();
        return View(item);
    }

    // POST: ItemController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Update(UpdateItemDto item)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
    public async Task<ActionResult> Delete(int id)
    {
       
            await _repositoryManager.Item.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
     
    }
}

MedLab_Dapper/Views/Shared/_DefaultLayout.cshtml
@*

    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title> Medilab </title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="/mediLab/assets/img/favicon.png" rel="icon">
    <link href="/mediLab/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/mediLab/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/mediLab/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/mediLab/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="/mediLab/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="/mediLab/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/mediLab/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="/mediLab/assets/css/main.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Medilab
    * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
    * Updated: Aug 07 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body class="index-page">

    <header id="header" class="header sticky-top">

        <div class="topbar d-flex align-items-center">
            <div class="container d-flex justify-content-center justify-content-md-between">
                <div class="contact-info d-flex align-items-center">
                    <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">medilab1234@medilab.com</a></i>
                    <i class="bi bi-phone d-flex align-items-center ms-4"><span>(0343) 435 576 45 67</span></i>
                </div>
                <div class="social-links d-none d-md-flex align-items-center">
                    <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
                    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>
        </div><!-- End Top Bar -->

        <div class="branding d-flex align-items-center">

            <div class="container position-relative d-flex align-items-center justify-content-between">
                <a href="index.html" class="logo d-flex align-items-center me-auto">
                    <!-- Uncomment the line below if you also wish to use an image logo -->
                    <!-- <img src="assets/img/logo.png" alt=""> -->
                    <h1 class="sitename">Medilab</h1>
                </a>

                <nav id="navmenu" class="navmenu">
                    <ul>
                        <li><a href="#hero" class="active">Ana sayfa<br></a></li>
                        <li><a href="#about">Hakkımızda</a></li>
                        <li><a href="#services">Hizmet</a></li>
                        <li><a href="#departments">Departman</a></li>
                        <li><a href="#doctors">Doktor</a></li>
                        
                        <li><a href="#contact">İletişim</a></li>
                    </ul>
                    <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
                </nav>

                <a class="cta-btn d-none d-sm-block" href="#appointment">Randevu Alın</a>

            </div>

        </div>

    </header>

     @RenderBody()

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="/mediLab/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/mediLab/assets/vendor/php-email-form/validate.js"></script>
    <script src="/mediLab/assets/vendor/aos/aos.js"></script>
    <script src="/mediLab/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="/mediLab/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="/mediLab/assets/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="/mediLab/assets/js/main.js"></script>

</body>

</html>

MedLab_Dapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]- Medilab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedLab_Dapper.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" 
    integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light-subtle border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Doctor" asp-action="Index">Medilab</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Doctor" asp-action="Index">Doktor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Departman</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="text-dark">Hakkımızda</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-action="Index" asp-controller="About">Hakkımızda Bilgisi</a></li>
                                <li><a class="dropdown-item" asp-action="Index" asp-controller="Item">Itemler</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="text-dark">Diğer Sayfalar</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Service" asp-action="Index">Hizmetler</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Contact" asp-action="Index">İletişim</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-controller="Testimonial" asp-action="Index">Değerlendirme</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="SocialMedia" asp-action="Index">Sosyal Medya</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="FrequentlyQuestion" asp-action="Index">En çok Sorulan Sorular</a>
                                </li>

                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Gallery" asp-action="Index">Gellery</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Appointment" asp-action="Index">Randevuler</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item text-dark" asp-controller="Message" asp-action="Index">Gelen Mesajlar</a>
                                </li>
                            </ul>

                            
                        </li>
                       
                       
                        


                    </ul> 
                    <a asp-action="Index" asp-controller="Home" class="text-dark text-end">

                        <i class="fa-solid fa-arrow-left"></i>
                        Siteye Git
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 px-3 mb-2">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MedLab_Dapper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>